export const products = [
    {
        id: 1,
        name: "Apple iPhone 14 Pro Max",
        currPrice: 79999,
        originalPrice: 99999,
        image: "https://m.media-amazon.com/images/I/81fxjeu8fdL._AC_UY327_FMwebp_QL65_.jpg",
        category: "Mobiles",
        brand: "Apple",
        rating: 4.8,
        reviews: 1245,
        keywords:"MobileSmartphoneiphoneapple",
        inStock: true,
    },
    {
        id: 2,
        name: "Samsung Galaxy S23",
        currPrice: 74999,
        originalPrice: 99999,
        image: "https://m.media-amazon.com/images/I/61-E0V81kBL._AC_UY327_FMwebp_QL65_.jpg",
        category: "Mobiles",
        brand: "Samsung",
        rating: 3.7,
        keywords:"MobileSmartphonesgalaxys23samsung",
        reviews: 980,
        inStock: true,
    },
    {
        id: 3,
        name: "Sony WH-1000XM5",
        currPrice: 29999,
        originalPrice: 34999,
        image: "https://m.media-amazon.com/images/I/71sLOtsK2UL._AC_UY327_FMwebp_QL65_.jpg",
        category: "Electronics",
        brand: "Sony",
        rating: 2.6,
        keywords:"EarphoneHeadphone",
        reviews: 560,
        inStock: true,
    },
    {
        id: 5,
        name: "Nike Air Max Shoes",
        currPrice: 11999,
        originalPrice: 14999,
        image: "https://m.media-amazon.com/images/I/51kqx6VFzuL._AC_UL480_FMwebp_QL65_.jpg",
        category:"Footwear",
        brand: "Nike",
        rating: 3.3,
        keywords:"FootwearShoesjordan",
        reviews: 890,
        inStock: true,
    },
    {
        id: 6,
        name: "Sony 55-inch 4K Ultra TV",
        currPrice: 59999,
        originalPrice: 74999,
        image: "https://m.media-amazon.com/images/I/81h-r-3hioL._AC_UY327_FMwebp_QL65_.jpg",
        category: "Televisions",
        brand: "Sony",
        rating: 4.7,
        keywords:"TelevisionTv",
        reviews: 645,
        inStock: true,
    },
    {
        id: 7,
        name: "Samsung 253L Frost-Free",
        currPrice: 22999,
        originalPrice: 27999,
        image: "https://m.media-amazon.com/images/I/71EQUl0vWUL._AC_UY327_FMwebp_QL65_.jpg",
        category: "Home Appliances",
        brand: "Samsung",
        rating: 2.4,
        keywords:"RefrigiratorFridge",
        reviews: 432,
        inStock: true,
    },
    {
        id: 8,
        name: "OnePlus 11R 5G",
        currPrice: 39999,
        originalPrice: 44999,
        image: "https://m.media-amazon.com/images/I/61Io5-ojWUL._AC_UY327_FMwebp_QL65_.jpg",
        category: "Mobiles",
        brand: "OnePlus",
        rating: 1.5,
        keywords:"MobileSmartphone",
        reviews: 1231,
        inStock: true,
    },
    {
        id: 9,
        name: "HP Pavilion 15 Laptop",
        currPrice: 69999,
        originalPrice: 79999,
        image: "https://m.media-amazon.com/images/I/71ZQWT7IIyL._AC_UY327_FMwebp_QL65_.jpg",
        category: "Laptops",
        brand: "HP",
        rating: 3.7,
        keywords:"LaptopsComputer",
        reviews: 412,
        inStock: true,
    },
    {
        id: 10,
        name: "Adidas Running Shoes",
        currPrice: 6999,
        originalPrice: 9999,
        image: "https://m.media-amazon.com/images/I/51OKe40vwvL._AC_UL480_FMwebp_QL65_.jpg",
        category: "Footwear",
        brand: "Adidas",
        keywords:"FootwearShoes",
        rating: 4.0,
        reviews: 789,
        inStock: true,
    },
    {
        id: 11,
        name: "Apple MacBook Air M2",
        currPrice: 114999,
        originalPrice: 129999,
        image: "https://m.media-amazon.com/images/I/71RDgtHsREL._AC_UY327_FMwebp_QL65_.jpg",
        category: "Laptops",
        brand: "Apple",
        rating: 5,
        keywords:"LaptopsComputer",
        reviews: 954,
        inStock: true,
    },
    {
        id: 12,
        name: "LG 1.5 Ton 5 Star AC",
        currPrice: 35999,
        originalPrice: 41999,
        image: "https://m.media-amazon.com/images/I/512nxe1Tq+L._AC_UY327_FMwebp_QL65_.jpg",
        category: "Home Appliances",
        brand: "LG",
        rating: 2.2,
        keywords:"AcCooler",
        keywords:"ACcooler",
        reviews: 632,
        inStock: false,
    },
    {
        id: 13,
        name: "Realme GT 2 Pro 5G",
        currPrice: 44999,
        originalPrice: 49999,
        image: "https://m.media-amazon.com/images/I/811oKUF9GVL._AC_UY327_FMwebp_QL65_.jpg",
        category: "Mobiles",
        brand: "Realme",
        rating: 3.3,
        keywords:"MobilesSmartphone",
        reviews: 811,
        inStock: true,
    },
    {
        id: 14,
        name: "Mi Smart Band 7 Pro",
        currPrice: 4999,
        originalPrice: 5999,
        image: "https://m.media-amazon.com/images/I/71Tk5OPf9BL._AC_UY327_FMwebp_QL65_.jpg",
        category: "Wearables",
        brand: "Xiaomi",
        keywords:"WatchSmartwatch",
        rating: 4.2,
        reviews: 1784,
        inStock: true,
    },
    {
        id: 15,
        name: "Dell XPS 13 Laptop",
        currPrice: 124999,
        originalPrice: 139999,
        image: "https://m.media-amazon.com/images/I/61s1d1AhQwL._AC_UY327_FMwebp_QL65_.jpg",
        category: "Laptops",
        brand: "Dell",
        keywords:"LaptopsComputer",
        rating: 4.8,
        reviews: 487,
        inStock: true,
    },
];


